### ISSUE TITLE
How to setup with .html file.

### ISSUE THREAD

**Issue by micronyks** [vadymshymko/PureJSCarousel#1]
Please provide .html file also. it should be there which is missing. Being author you know how to setup everything. so please help to setup or simply provide .html file with required content.

https://plnkr.co/edit/EfGNziEnebb6JVjlvmXi?p=preview
please check and help.

**Comment by vadymshymko** [comment]
Paste in browser - `view-source:https://vadymshymko.github.io/portfolio/purejscarousel/`
