### ISSUE TITLE
slide using mouse or hand not working

### ISSUE THREAD

**Issue by Prem18mca** [vadymshymko/PureJSCarousel#2]

**Comment by vadymshymko** [comment]
First of all, I would like to ask you, that's what
  - provide a more detailed description in the future.

Regarding the current issue - the problem with the touchpad is fixed, scrolling with the mouse is not supported

**Comment by vadymshymko** [comment]
> _No description provided._

First of all, I would like to ask you, that's what
  - provide a more detailed description in the future.

Regarding the current issue - the problem with the touchpad is fixed, scrolling with the mouse is not supported
