### ISSUE TITLE
Bugs in the start and stop methods

### ISSUE THREAD

**Issue by Samuelbdesouza** [vadymshymko/PureJSCarousel#3]
Hello,
I'm using your carousel script, but I found a problem in the startAutoplay method and stopAutoplay, so I understand just call the YourVariable.startAutoplay (autoplayDirection) method, but when doing this the following error is returned: YourVariable.stopAutoplay is not a function.
can you help me?

**Comment by vadymshymko** [comment]
Sorry, but this is a mistake in the documentation. These methods are currently unavailable. But will be returned soon

**Comment by vadymshymko** [comment]
> Hello,
> I'm using your carousel script, but I found a problem in the startAutoplay method and stopAutoplay, so I understand just call the YourVariable.startAutoplay (autoplayDirection) method, but when doing this the following error is returned: YourVariable.stopAutoplay is not a function.
> can you help me?

Sorry, but this is a mistake in the documentation. These methods are currently unavailable. But will be returned soon

**Comment by vadymshymko** [comment]
@Samuelbdesouza  please, try to use this version -  https://github.com/vadymshymko/PureJSCarousel/blob/master/purejscarousel.3.0.0.js
