### ISSUE TITLE
Revise margin-left to transform: translate-x to satisfy current Lighthouse Audit

### ISSUE THREAD

**Issue by tmb-github** [vadymshymko/PureJSCarousel#4]
This is a great carousel. The most recent Chrome Lighthouse Audit flags transitions that are not composited, such as the transition on margin-left in the routine. This can be solved by converting the margin-left edit to a transform: translate-x edit, with a transition on transform. See https://developers.google.com/web/fundamentals/performance/rendering/stick-to-compositor-only-properties-and-manage-layer-count

**Comment by vadymshymko** [comment]
@tmb-github Done in https://github.com/vadymshymko/PureJSCarousel/blob/master/purejscarousel.3.0.0.js
