### ISSUE TITLE
unable to have multi-line text in  slide

### ISSUE THREAD

**Issue by gowridev** [vadymshymko/PureJSCarousel#5]
I am unable to write multi-line text in slide. please guide me what needs to be fixed or example

**Comment by vadymshymko** [comment]
@gowridev You can wrap your text in some tag. For example:
```
<div class="slide"><p style="  line-height: 1.5;
  display: flex;
  height: 100%;
  margin: 0;
  align-items: center;">Slide 1 with some looooooooooong and very multiline text</p></div>
```

example: https://vadymshymko.github.io/portfolio/purejscarousel/?example (first slide)
